# screen properties
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# asteroid properties
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# player properties
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 240
PLAYER_SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 600
PLAYER_SHOOT_COOLDOWN = 0.3

# colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
